### PR TITLE
Functor and Applicative instances for ExprArr

### PR DESCRIPTION
**Pull request by bergmark**
```
    q = (,,,,)
     <$> pure (Nothing :: Maybe (Wire Int))
     <*> (Just <$> constant (Post.author      post))
     <*> (Just <$> constant (Post.createdTime post))
     <*> (Just <$> constant (Post.title       post))
     <*> (Just <$> constant (Post.content     post))
```

<=>

```
  q = proc () -> do
          author  <- constant (Post.author post) -< ()
          time <- constant (Post.createdTime post) -< ()
          title <- constant (Post.title post) -< ()
          content <- constant (Post.content post) -< ()
          returnA -< (Nothing :: Maybe (Wire Int), Just author, Just time, Just title, Just content)
```

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Neat, although MakeExpr.hs now has a neater way of doing this :)

**Comment by tomjaguarpaw** [comment]
Do you know how I can merge this against dev?  Alternatively can you reissue the pull request against dev?  Thanks.

**Comment by bergmark** [comment]
I don't think i can change what the PR is against, but you can merge it from the command line, or I can open a new one.

I wasn't aware of the dev branch, should I always make PRs against that?

**Comment by dbp** [comment]
@tomjaguarpaw Just curious (sorry for lurking!), is MakeExpr.hs online somewhere?

**Comment by tomjaguarpaw** [comment]
Yes always against dev please.

Either I'll make a new pull request against your branch or you can.  Whoever gets round to it first!

**Comment by tomjaguarpaw** [comment]
@dbp: Oops I guess I haven't pushed that yet!  MakeExpr goodness is on its way though ... :)

**Comment by tomjaguarpaw** [comment]
@dbp This does now exist:  https://github.com/karamaan/karamaan-opaleye/blob/dev/Karamaan/Opaleye/MakeExpr.hs

**Pull request closed without merging**
