### PR TITLE
Implement 'limit'.

### PR DESCRIPTION
**Pull request by hesselink**
Seems to be as simple as the TODO promised :)

### CODE REVIEW

**Comment by hesselink** [comment]
I just realized that since this is small, and also useless without ordering, it might as well live in that module. If you agree, please hold off on this until ordering is merged. I'll then rebase this on top of that.

**Comment by tomjaguarpaw** [comment]
Makes sense to me.

**Comment by hesselink** [comment]
One thing I've noticed is that haskelldb allows you to limit multiple times, and consequently so does my simple implementation of limit in opaleye. This means that if you do `limit 1 $ limit 2 someQuery` you get sql like `... LIMIT 1 LIMIT 2`, which is invalid. This should probably be fixed in haskelldb, right?

**Comment by tomjaguarpaw** [comment]
Well spotted.  I agree it should be fixed in HaskellDB.

**Comment by tomjaguarpaw** [comment]
Ready for this now, although on reflection I don't mind creating a new module just for this and offset.  I'll leave it up to you.

**Comment by hesselink** [comment]
I still think it makes sense for these things to all be in the same module. Limiting or offsets without ordering is not really possible, since it's undefined what records will be returned. By putting them in separate modules, we'd just force people to import two modules when they want to limit.

I've rebased this on top of the current `dev` branch.

**Comment by tomjaguarpaw** [comment]
Looks great, and your rationale for putting them in the same module is a good one.

**Pull request merged**
